### ISSUE TITLE
README.md Small Mistakes

### ISSUE THREAD

**Issue by Py08** [V39Pygamer/Space-Invaders-Game#1]
In your README.md, the spelling of 'similar' is wrong and the picture is showing the alt text so please check it.

**Comment by vismodo** [comment]
The image is a link to your C: offline drive. You need to add the images via upload and enter the link to it.

https://github.com/V39Pygamer/Space-Invaders-Game/blob/9aa489b9d3baa817d5dfac8d66e2a44bffe34b55/README.md#L5

Convert it to:

```
![image](https://github.com/V39Pygamer/Space-Invaders-Game/blob/master/space_invaders_screenshot.png)
```

**Comment by V39Pygamer** [comment]
I have corrected it thanks for informing

**Comment by V39Pygamer** [comment]
>

**Comment by vismodo** [comment]
Sorry, But the problem still persists
